// src/constants/countryCodes.js

export const COUNTRY_CODES = [
  { value: "+93", label: "+93 (AF)", country: "Afghanistan", code: "AF" },
  { value: "+355", label: "+355 (AL)", country: "Albania", code: "AL" },
  { value: "+213", label: "+213 (DZ)", country: "Algeria", code: "DZ" },
  { value: "+1684", label: "+1684 (AS)", country: "American Samoa", code: "AS" },
  { value: "+376", label: "+376 (AD)", country: "Andorra", code: "AD" },
  { value: "+244", label: "+244 (AO)", country: "Angola", code: "AO" },
  { value: "+1264", label: "+1264 (AI)", country: "Anguilla", code: "AI" },
  { value: "+672", label: "+672 (AQ)", country: "Antarctica", code: "AQ" },
  { value: "+1268", label: "+1268 (AG)", country: "Antigua and Barbuda", code: "AG" },
  { value: "+54", label: "+54 (AR)", country: "Argentina", code: "AR" },
  { value: "+374", label: "+374 (AM)", country: "Armenia", code: "AM" },
  { value: "+297", label: "+297 (AW)", country: "Aruba", code: "AW" },
  { value: "+61", label: "+61 (AU)", country: "Australia", code: "AU" },
  { value: "+43", label: "+43 (AT)", country: "Austria", code: "AT" },
  { value: "+994", label: "+994 (AZ)", country: "Azerbaijan", code: "AZ" },
  { value: "+1242", label: "+1242 (BS)", country: "Bahamas", code: "BS" },
  { value: "+973", label: "+973 (BH)", country: "Bahrain", code: "BH" },
  { value: "+880", label: "+880 (BD)", country: "Bangladesh", code: "BD" },
  { value: "+1246", label: "+1246 (BB)", country: "Barbados", code: "BB" },
  { value: "+375", label: "+375 (BY)", country: "Belarus", code: "BY" },
  { value: "+32", label: "+32 (BE)", country: "Belgium", code: "BE" },
  { value: "+501", label: "+501 (BZ)", country: "Belize", code: "BZ" },
  { value: "+229", label: "+229 (BJ)", country: "Benin", code: "BJ" },
  { value: "+1441", label: "+1441 (BM)", country: "Bermuda", code: "BM" },
  { value: "+975", label: "+975 (BT)", country: "Bhutan", code: "BT" },
  { value: "+591", label: "+591 (BO)", country: "Bolivia", code: "BO" },
  { value: "+387", label: "+387 (BA)", country: "Bosnia and Herzegovina", code: "BA" },
  { value: "+267", label: "+267 (BW)", country: "Botswana", code: "BW" },
  { value: "+55", label: "+55 (BR)", country: "Brazil", code: "BR" },
  { value: "+246", label: "+246 (IO)", country: "British Indian Ocean Territory", code: "IO" },
  { value: "+673", label: "+673 (BN)", country: "Brunei", code: "BN" },
  { value: "+359", label: "+359 (BG)", country: "Bulgaria", code: "BG" },
  { value: "+226", label: "+226 (BF)", country: "Burkina Faso", code: "BF" },
  { value: "+257", label: "+257 (BI)", country: "Burundi", code: "BI" },
  { value: "+855", label: "+855 (KH)", country: "Cambodia", code: "KH" },
  { value: "+237", label: "+237 (CM)", country: "Cameroon", code: "CM" },
  { value: "+1", label: "+1 (CA)", country: "Canada", code: "CA" },
  { value: "+238", label: "+238 (CV)", country: "Cape Verde", code: "CV" },
  { value: "+1345", label: "+1345 (KY)", country: "Cayman Islands", code: "KY" },
  { value: "+236", label: "+236 (CF)", country: "Central African Republic", code: "CF" },
  { value: "+235", label: "+235 (TD)", country: "Chad", code: "TD" },
  { value: "+56", label: "+56 (CL)", country: "Chile", code: "CL" },
  { value: "+86", label: "+86 (CN)", country: "China", code: "CN" },
  { value: "+61", label: "+61 (CX)", country: "Christmas Island", code: "CX" },
  { value: "+61", label: "+61 (CC)", country: "Cocos (Keeling) Islands", code: "CC" },
  { value: "+57", label: "+57 (CO)", country: "Colombia", code: "CO" },
  { value: "+269", label: "+269 (KM)", country: "Comoros", code: "KM" },
  { value: "+242", label: "+242 (CG)", country: "Congo (Brazzaville)", code: "CG" },
  { value: "+243", label: "+243 (CD)", country: "Congo (Kinshasa)", code: "CD" },
  { value: "+682", label: "+682 (CK)", country: "Cook Islands", code: "CK" },
  { value: "+506", label: "+506 (CR)", country: "Costa Rica", code: "CR" },
  { value: "+225", label: "+225 (CI)", country: "Côte d'Ivoire", code: "CI" },
  { value: "+385", label: "+385 (HR)", country: "Croatia", code: "HR" },
  { value: "+53", label: "+53 (CU)", country: "Cuba", code: "CU" },
  { value: "+357", label: "+357 (CY)", country: "Cyprus", code: "CY" },
  { value: "+420", label: "+420 (CZ)", country: "Czech Republic", code: "CZ" },
  { value: "+45", label: "+45 (DK)", country: "Denmark", code: "DK" },
  { value: "+253", label: "+253 (DJ)", country: "Djibouti", code: "DJ" },
  { value: "+1767", label: "+1767 (DM)", country: "Dominica", code: "DM" },
  { value: "+1849", label: "+1849 (DO)", country: "Dominican Republic", code: "DO" },
  { value: "+593", label: "+593 (EC)", country: "Ecuador", code: "EC" },
  { value: "+20", label: "+20 (EG)", country: "Egypt", code: "EG" },
  { value: "+503", label: "+503 (SV)", country: "El Salvador", code: "SV" },
  { value: "+240", label: "+240 (GQ)", country: "Equatorial Guinea", code: "GQ" },
  { value: "+291", label: "+291 (ER)", country: "Eritrea", code: "ER" },
  { value: "+372", label: "+372 (EE)", country: "Estonia", code: "EE" },
  { value: "+268", label: "+268 (SZ)", country: "Eswatini", code: "SZ" },
  { value: "+251", label: "+251 (ET)", country: "Ethiopia", code: "ET" },
  { value: "+500", label: "+500 (FK)", country: "Falkland Islands", code: "FK" },
  { value: "+298", label: "+298 (FO)", country: "Faroe Islands", code: "FO" },
  { value: "+679", label: "+679 (FJ)", country: "Fiji", code: "FJ" },
  { value: "+358", label: "+358 (FI)", country: "Finland", code: "FI" },
  { value: "+33", label: "+33 (FR)", country: "France", code: "FR" },
  { value: "+594", label: "+594 (GF)", country: "French Guiana", code: "GF" },
  { value: "+689", label: "+689 (PF)", country: "French Polynesia", code: "PF" },
  { value: "+241", label: "+241 (GA)", country: "Gabon", code: "GA" },
  { value: "+220", label: "+220 (GM)", country: "Gambia", code: "GM" },
  { value: "+995", label: "+995 (GE)", country: "Georgia", code: "GE" },
  { value: "+49", label: "+49 (DE)", country: "Germany", code: "DE" },
  { value: "+233", label: "+233 (GH)", country: "Ghana", code: "GH" },
  { value: "+350", label: "+350 (GI)", country: "Gibraltar", code: "GI" },
  { value: "+30", label: "+30 (GR)", country: "Greece", code: "GR" },
  { value: "+299", label: "+299 (GL)", country: "Greenland", code: "GL" },
  { value: "+1473", label: "+1473 (GD)", country: "Grenada", code: "GD" },
  { value: "+590", label: "+590 (GP)", country: "Guadeloupe", code: "GP" },
  { value: "+1671", label: "+1671 (GU)", country: "Guam", code: "GU" },
  { value: "+502", label: "+502 (GT)", country: "Guatemala", code: "GT" },
  { value: "+44", label: "+44 (GG)", country: "Guernsey", code: "GG" },
  { value: "+224", label: "+224 (GN)", country: "Guinea", code: "GN" },
  { value: "+245", label: "+245 (GW)", country: "Guinea-Bissau", code: "GW" },
  { value: "+592", label: "+592 (GY)", country: "Guyana", code: "GY" },
  { value: "+509", label: "+509 (HT)", country: "Haiti", code: "HT" },
  { value: "+504", label: "+504 (HN)", country: "Honduras", code: "HN" },
  { value: "+852", label: "+852 (HK)", country: "Hong Kong", code: "HK" },
  { value: "+36", label: "+36 (HU)", country: "Hungary", code: "HU" },
  { value: "+354", label: "+354 (IS)", country: "Iceland", code: "IS" },
  { value: "+91", label: "+91 (IN)", country: "India", code: "IN" },
  { value: "+62", label: "+62 (ID)", country: "Indonesia", code: "ID" },
  { value: "+98", label: "+98 (IR)", country: "Iran", code: "IR" },
  { value: "+964", label: "+964 (IQ)", country: "Iraq", code: "IQ" },
  { value: "+353", label: "+353 (IE)", country: "Ireland", code: "IE" },
  { value: "+44", label: "+44 (IM)", country: "Isle of Man", code: "IM" },
  { value: "+972", label: "+972 (IL)", country: "Israel", code: "IL" },
  { value: "+39", label: "+39 (IT)", country: "Italy", code: "IT" },
  { value: "+1876", label: "+1876 (JM)", country: "Jamaica", code: "JM" },
  { value: "+81", label: "+81 (JP)", country: "Japan", code: "JP" },
  { value: "+44", label: "+44 (JE)", country: "Jersey", code: "JE" },
  { value: "+962", label: "+962 (JO)", country: "Jordan", code: "JO" },
  { value: "+7", label: "+7 (KZ)", country: "Kazakhstan", code: "KZ" },
  { value: "+254", label: "+254 (KE)", country: "Kenya", code: "KE" },
  { value: "+686", label: "+686 (KI)", country: "Kiribati", code: "KI" },
  { value: "+850", label: "+850 (KP)", country: "North Korea", code: "KP" },
  { value: "+82", label: "+82 (KR)", country: "South Korea", code: "KR" },
  { value: "+965", label: "+965 (KW)", country: "Kuwait", code: "KW" },
  { value: "+996", label: "+996 (KG)", country: "Kyrgyzstan", code: "KG" },
  { value: "+856", label: "+856 (LA)", country: "Laos", code: "LA" },
  { value: "+371", label: "+371 (LV)", country: "Latvia", code: "LV" },
  { value: "+961", label: "+961 (LB)", country: "Lebanon", code: "LB" },
  { value: "+266", label: "+266 (LS)", country: "Lesotho", code: "LS" },
  { value: "+231", label: "+231 (LR)", country: "Liberia", code: "LR" },
  { value: "+218", label: "+218 (LY)", country: "Libya", code: "LY" },
  { value: "+423", label: "+423 (LI)", country: "Liechtenstein", code: "LI" },
  { value: "+370", label: "+370 (LT)", country: "Lithuania", code: "LT" },
  { value: "+352", label: "+352 (LU)", country: "Luxembourg", code: "LU" },
  { value: "+853", label: "+853 (MO)", country: "Macau", code: "MO" },
  { value: "+389", label: "+389 (MK)", country: "Macedonia", code: "MK" },
  { value: "+261", label: "+261 (MG)", country: "Madagascar", code: "MG" },
  { value: "+265", label: "+265 (MW)", country: "Malawi", code: "MW" },
  { value: "+60", label: "+60 (MY)", country: "Malaysia", code: "MY" },
  { value: "+960", label: "+960 (MV)", country: "Maldives", code: "MV" },
  { value: "+223", label: "+223 (ML)", country: "Mali", code: "ML" },
  { value: "+356", label: "+356 (MT)", country: "Malta", code: "MT" },
  { value: "+692", label: "+692 (MH)", country: "Marshall Islands", code: "MH" },
  { value: "+596", label: "+596 (MQ)", country: "Martinique", code: "MQ" },
  { value: "+222", label: "+222 (MR)", country: "Mauritania", code: "MR" },
  { value: "+230", label: "+230 (MU)", country: "Mauritius", code: "MU" },
  { value: "+262", label: "+262 (YT)", country: "Mayotte", code: "YT" },
  { value: "+52", label: "+52 (MX)", country: "Mexico", code: "MX" },
  { value: "+691", label: "+691 (FM)", country: "Micronesia", code: "FM" },
  { value: "+373", label: "+373 (MD)", country: "Moldova", code: "MD" },
  { value: "+377", label: "+377 (MC)", country: "Monaco", code: "MC" },
  { value: "+976", label: "+976 (MN)", country: "Mongolia", code: "MN" },
  { value: "+382", label: "+382 (ME)", country: "Montenegro", code: "ME" },
  { value: "+1664", label: "+1664 (MS)", country: "Montserrat", code: "MS" },
  { value: "+212", label: "+212 (MA)", country: "Morocco", code: "MA" },
  { value: "+258", label: "+258 (MZ)", country: "Mozambique", code: "MZ" },
  { value: "+95", label: "+95 (MM)", country: "Myanmar", code: "MM" },
  { value: "+264", label: "+264 (NA)", country: "Namibia", code: "NA" },
  { value: "+674", label: "+674 (NR)", country: "Nauru", code: "NR" },
  { value: "+977", label: "+977 (NP)", country: "Nepal", code: "NP" },
  { value: "+31", label: "+31 (NL)", country: "Netherlands", code: "NL" },
  { value: "+599", label: "+599 (AN)", country: "Netherlands Antilles", code: "AN" },
  { value: "+687", label: "+687 (NC)", country: "New Caledonia", code: "NC" },
  { value: "+64", label: "+64 (NZ)", country: "New Zealand", code: "NZ" },
  { value: "+505", label: "+505 (NI)", country: "Nicaragua", code: "NI" },
  { value: "+227", label: "+227 (NE)", country: "Niger", code: "NE" },
  { value: "+234", label: "+234 (NG)", country: "Nigeria", code: "NG" },
  { value: "+683", label: "+683 (NU)", country: "Niue", code: "NU" },
  { value: "+672", label: "+672 (NF)", country: "Norfolk Island", code: "NF" },
  { value: "+1670", label: "+1670 (MP)", country: "Northern Mariana Islands", code: "MP" },
  { value: "+47", label: "+47 (NO)", country: "Norway", code: "NO" },
  { value: "+968", label: "+968 (OM)", country: "Oman", code: "OM" },
  { value: "+92", label: "+92 (PK)", country: "Pakistan", code: "PK" },
  { value: "+680", label: "+680 (PW)", country: "Palau", code: "PW" },
  { value: "+970", label: "+970 (PS)", country: "Palestine", code: "PS" },
  { value: "+507", label: "+507 (PA)", country: "Panama", code: "PA" },
  { value: "+675", label: "+675 (PG)", country: "Papua New Guinea", code: "PG" },
  { value: "+595", label: "+595 (PY)", country: "Paraguay", code: "PY" },
  { value: "+51", label: "+51 (PE)", country: "Peru", code: "PE" },
  { value: "+63", label: "+63 (PH)", country: "Philippines", code: "PH" },
  { value: "+48", label: "+48 (PL)", country: "Poland", code: "PL" },
  { value: "+351", label: "+351 (PT)", country: "Portugal", code: "PT" },
  { value: "+1939", label: "+1939 (PR)", country: "Puerto Rico", code: "PR" },
  { value: "+974", label: "+974 (QA)", country: "Qatar", code: "QA" },
  { value: "+262", label: "+262 (RE)", country: "Réunion", code: "RE" },
  { value: "+40", label: "+40 (RO)", country: "Romania", code: "RO" },
  { value: "+7", label: "+7 (RU)", country: "Russia", code: "RU" },
  { value: "+250", label: "+250 (RW)", country: "Rwanda", code: "RW" },
  { value: "+590", label: "+590 (BL)", country: "Saint Barthélemy", code: "BL" },
  { value: "+290", label: "+290 (SH)", country: "Saint Helena", code: "SH" },
  { value: "+1869", label: "+1869 (KN)", country: "Saint Kitts and Nevis", code: "KN" },
  { value: "+1758", label: "+1758 (LC)", country: "Saint Lucia", code: "LC" },
  { value: "+590", label: "+590 (MF)", country: "Saint Martin", code: "MF" },
  { value: "+508", label: "+508 (PM)", country: "Saint Pierre and Miquelon", code: "PM" },
  { value: "+1784", label: "+1784 (VC)", country: "Saint Vincent and the Grenadines", code: "VC" },
  { value: "+685", label: "+685 (WS)", country: "Samoa", code: "WS" },
  { value: "+378", label: "+378 (SM)", country: "San Marino", code: "SM" },
  { value: "+239", label: "+239 (ST)", country: "Sao Tome and Principe", code: "ST" },
  { value: "+966", label: "+966 (SA)", country: "Saudi Arabia", code: "SA" },
  { value: "+221", label: "+221 (SN)", country: "Senegal", code: "SN" },
  { value: "+381", label: "+381 (RS)", country: "Serbia", code: "RS" },
  { value: "+248", label: "+248 (SC)", country: "Seychelles", code: "SC" },
  { value: "+232", label: "+232 (SL)", country: "Sierra Leone", code: "SL" },
  { value: "+65", label: "+65 (SG)", country: "Singapore", code: "SG" },
  { value: "+421", label: "+421 (SK)", country: "Slovakia", code: "SK" },
  { value: "+386", label: "+386 (SI)", country: "Slovenia", code: "SI" },
  { value: "+677", label: "+677 (SB)", country: "Solomon Islands", code: "SB" },
  { value: "+252", label: "+252 (SO)", country: "Somalia", code: "SO" },
  { value: "+27", label: "+27 (ZA)", country: "South Africa", code: "ZA" },
  { value: "+211", label: "+211 (SS)", country: "South Sudan", code: "SS" },
  { value: "+34", label: "+34 (ES)", country: "Spain", code: "ES" },
  { value: "+94", label: "+94 (LK)", country: "Sri Lanka", code: "LK" },
  { value: "+249", label: "+249 (SD)", country: "Sudan", code: "SD" },
  { value: "+597", label: "+597 (SR)", country: "Suriname", code: "SR" },
  { value: "+47", label: "+47 (SJ)", country: "Svalbard and Jan Mayen", code: "SJ" },
  { value: "+46", label: "+46 (SE)", country: "Sweden", code: "SE" },
  { value: "+41", label: "+41 (CH)", country: "Switzerland", code: "CH" },
  { value: "+963", label: "+963 (SY)", country: "Syria", code: "SY" },
  { value: "+886", label: "+886 (TW)", country: "Taiwan", code: "TW" },
  { value: "+992", label: "+992 (TJ)", country: "Tajikistan", code: "TJ" },
  { value: "+255", label: "+255 (TZ)", country: "Tanzania", code: "TZ" },
  { value: "+66", label: "+66 (TH)", country: "Thailand", code: "TH" },
  { value: "+228", label: "+228 (TG)", country: "Togo", code: "TG" },
  { value: "+690", label: "+690 (TK)", country: "Tokelau", code: "TK" },
  { value: "+676", label: "+676 (TO)", country: "Tonga", code: "TO" },
  { value: "+1868", label: "+1868 (TT)", country: "Trinidad and Tobago", code: "TT" },
  { value: "+216", label: "+216 (TN)", country: "Tunisia", code: "TN" },
  { value: "+90", label: "+90 (TR)", country: "Turkey", code: "TR" },
  { value: "+993", label: "+993 (TM)", country: "Turkmenistan", code: "TM" },
  { value: "+1649", label: "+1649 (TC)", country: "Turks and Caicos Islands", code: "TC" },
  { value: "+688", label: "+688 (TV)", country: "Tuvalu", code: "TV" },
  { value: "+256", label: "+256 (UG)", country: "Uganda", code: "UG" },
  { value: "+380", label: "+380 (UA)", country: "Ukraine", code: "UA" },
  { value: "+971", label: "+971 (AE)", country: "United Arab Emirates", code: "AE" },
  { value: "+44", label: "+44 (GB)", country: "United Kingdom", code: "GB" },
  { value: "+1", label: "+1 (US)", country: "United States", code: "US" },
  { value: "+598", label: "+598 (UY)", country: "Uruguay", code: "UY" },
  { value: "+998", label: "+998 (UZ)", country: "Uzbekistan", code: "UZ" },
  { value: "+678", label: "+678 (VU)", country: "Vanuatu", code: "VU" },
  { value: "+3906698", label: "+3906698 (VA)", country: "Vatican City", code: "VA" },
  { value: "+58", label: "+58 (VE)", country: "Venezuela", code: "VE" },
  { value: "+84", label: "+84 (VN)", country: "Vietnam", code: "VN" },
  { value: "+1284", label: "+1284 (VG)", country: "British Virgin Islands", code: "VG" },
  { value: "+1340", label: "+1340 (VI)", country: "U.S. Virgin Islands", code: "VI" },
  { value: "+681", label: "+681 (WF)", country: "Wallis and Futuna", code: "WF" },
  { value: "+967", label: "+967 (YE)", country: "Yemen", code: "YE" },
  { value: "+260", label: "+260 (ZM)", country: "Zambia", code: "ZM" },
  { value: "+263", label: "+263 (ZW)", country: "Zimbabwe", code: "ZW" }
];