// src/constants/product info data/gemstoneInfoData.js
// Total 124 gemstone cards – exact data ready to use

export const gemstonesCardInfoData = [
  { id: 1, name: "Amazonite", slug: "amazonite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Green to blue-green feldspar gemstone, known for its calming energy." },
  { id: 2, name: "Amethyst", slug: "amethyst", image: "/gemstone info images/amethyst/amethyst-main.jpg", shortDesc: "Purple quartz, February birthstone, promotes peace and clarity." },
  { id: 3, name: "Ametrine", slug: "ametrine", image: "/images/gemstones/placeholder.jpg", shortDesc: "Bicolor quartz combining purple amethyst and yellow citrine." },
  { id: 4, name: "Ammolite", slug: "ammolite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Iridescent fossilized ammonite shell, found only in Canada." },
  { id: 5, name: "Andalusite", slug: "andalusite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Pleochroic gem showing green, red, and yellow in one stone." },
  { id: 6, name: "Anyolite", slug: "anyolite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Green zoisite with ruby inclusions, also called ruby-in-zoisite." },
  { id: 7, name: "Apatite", slug: "apatite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Blue to green stone, often confused with tourmaline." },
  { id: 8, name: "Aquamarine", slug: "aquamarine", image: "/images/gemstones/placeholder.jpg", shortDesc: "Blue beryl, March birthstone, named after seawater." },
  { id: 9, name: "Aventurine", slug: "aventurine", image: "/images/gemstones/placeholder.jpg", shortDesc: "Green quartz with shimmering aventurescence from mica inclusions." },
  { id: 10, name: "Azurite", slug: "azurite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Deep blue copper carbonate, often found with malachite." },
  { id: 11, name: "Azurmalachite", slug: "azurmalachite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Natural mix of blue azurite and green malachite." },
  { id: 12, name: "Beryl", slug: "beryl", image: "/images/gemstones/placeholder.jpg", shortDesc: "Family of gems including emerald, aquamarine, and morganite." },
  { id: 13, name: "Benitoite", slug: "benitoite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Rare blue gem, California state gemstone." },
  { id: 14, name: "Birthstones", slug: "birthstones", image: "/images/gemstones/placeholder.jpg", shortDesc: "Traditional gemstones associated with each month." },
  { id: 15, name: "Bloodstone", slug: "bloodstone", image: "/images/gemstones/placeholder.jpg", shortDesc: "Dark green chalcedony with red spots, March birthstone." },
  { id: 16, name: "Boulder Opal", slug: "boulder-opal", image: "/images/gemstones/placeholder.jpg", shortDesc: "Opal with ironstone matrix, from Queensland, Australia." },
  { id: 17, name: "Carnelian", slug: "carnelian", image: "/images/gemstones/placeholder.jpg", shortDesc: "Orange to reddish-brown chalcedony, known for its warm color." },
  { id: 18, name: "Cat's Eye Opal", slug: "cats-eye-opal", image: "/images/gemstones/placeholder.jpg", shortDesc: "Opal with chatoyant band, also called 'cacholong'." },
  { id: 19, name: "Charoite", slug: "charoite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Violet to purple mineral found only in Siberia, Russia." },
  { id: 20, name: "Chrysoberyl", slug: "chrysoberyl", image: "/images/gemstones/placeholder.jpg", shortDesc: "Beryllium aluminate, includes alexandrite and cat's-eye." },
  { id: 21, name: "Chrysocolla", slug: "chrysocolla", image: "/images/gemstones/placeholder.jpg", shortDesc: "Blue-green copper silicate, often with turquoise-like color." },
  { id: 22, name: "Chrysoprase", slug: "chrysoprase", image: "/images/gemstones/placeholder.jpg", shortDesc: "Apple-green chalcedony, colored by nickel." },
  { id: 23, name: "Citrine", slug: "citrine", image: "/images/gemstones/placeholder.jpg", shortDesc: "Yellow to orange quartz, November birthstone." },
  { id: 24, name: "Cordierite", slug: "cordierite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Blue to violet gem, also known as iolite." },
  { id: 25, name: "Diamond", slug: "diamond", image: "/images/gemstones/placeholder.jpg", shortDesc: "Hardest natural material, symbol of eternal love." },
  { id: 26, name: "Dinosaur Bone", slug: "dinosaur-bone", image: "/images/gemstones/placeholder.jpg", shortDesc: "Fossilized bone agatized with quartz, also called gembone." },
  { id: 27, name: "Diopside", slug: "diopside", image: "/images/gemstones/placeholder.jpg", shortDesc: "Green pyroxene, chrome diopside is an emerald alternative." },
  { id: 28, name: "Dryhead Agate", slug: "dryhead-agate", image: "/images/gemstones/placeholder.jpg", shortDesc: "Rare red agate from Montana, prized by collectors." },
  { id: 29, name: "Emerald", slug: "emerald", image: "/images/gemstones/placeholder.jpg", shortDesc: "Green beryl, May birthstone, one of the 'big three' gems." },
  { id: 30, name: "Eudialyte", slug: "eudialyte", image: "/images/gemstones/placeholder.jpg", shortDesc: "Rare red to pink cyclosilicate from alkaline rocks." },
  { id: 31, name: "Fire Agate", slug: "fire-agate", image: "/images/gemstones/placeholder.jpg", shortDesc: "Agate with iridescent colors from iron oxide layers." },
  { id: 32, name: "Fire Opal", slug: "fire-opal", image: "/images/gemstones/placeholder.jpg", shortDesc: "Orange to red translucent opal, often without play-of-color." },
  { id: 33, name: "Fluorite", slug: "fluorite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Colorful calcium fluoride, often fluorescent under UV." },
  { id: 34, name: "Fossil Coral", slug: "fossil-coral", image: "/images/gemstones/placeholder.jpg", shortDesc: "Agatized coral from Florida or Indonesia." },
  { id: 35, name: "Gaspeite", slug: "gaspeite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Rare green nickel carbonate, used in jewelry." },
  { id: 36, name: "Garnet", slug: "garnet", image: "/images/gemstones/placeholder.jpg", shortDesc: "January birthstone, comes in all colors except blue." },
  { id: 37, name: "Gem Silica", slug: "gem-silica", image: "/images/gemstones/placeholder.jpg", shortDesc: "Blue-green chalcedony, rare and highly valued." },
  { id: 38, name: "Geodes", slug: "geodes", image: "/images/gemstones/placeholder.jpg", shortDesc: "Hollow rocks lined with crystals, often agate or quartz." },
  { id: 39, name: "Goldstone", slug: "goldstone", image: "/images/gemstones/placeholder.jpg", shortDesc: "Man-made glass with copper glitter, used as a gem simulant." },
  { id: 40, name: "Goshenite", slug: "goshenite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Colorless beryl, often used as a diamond simulant." },
  { id: 41, name: "Green Beryl", slug: "green-beryl", image: "/images/gemstones/placeholder.jpg", shortDesc: "Light green beryl, less intense color than emerald." },
  { id: 42, name: "Hawk's Eye", slug: "hawks-eye", image: "/images/gemstones/placeholder.jpg", shortDesc: "Blue-gray chatoyant quartz, a variety of tiger's eye." },
  { id: 43, name: "Helenite", slug: "helenite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Man-made glass from Mount St. Helens volcanic ash." },
  { id: 44, name: "Heliodor", slug: "heliodor", image: "/images/gemstones/placeholder.jpg", shortDesc: "Golden yellow to greenish-yellow beryl." },
  { id: 45, name: "Hematite", slug: "hematite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Metallic gray iron oxide, used for healing and grounding." },
  { id: 46, name: "Howlite", slug: "howlite", image: "/images/gemstones/placeholder.jpg", shortDesc: "White with gray veining, often dyed to imitate turquoise." },
  { id: 47, name: "Idocrase", slug: "idocrase", image: "/images/gemstones/placeholder.jpg", shortDesc: "Also known as vesuvianite, occurs in green, yellow, brown." },
  { id: 48, name: "Iolite", slug: "iolite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Blue to violet pleochroic gem, called 'water sapphire'." },
  { id: 49, name: "Iris Agate", slug: "iris-agate", image: "/images/gemstones/placeholder.jpg", shortDesc: "Agate with rainbow colors when backlit." },
  { id: 50, name: "Jade", slug: "jade", image: "/images/gemstones/placeholder.jpg", shortDesc: "Ancient gemstone, comes as jadeite (rare) and nephrite." },
  { id: 51, name: "Jadeite", slug: "jadeite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Rarer and more valuable form of jade, imperial green prized." },
  { id: 52, name: "Jasper", slug: "jasper", image: "/images/gemstones/placeholder.jpg", shortDesc: "Opaque chalcedony, often multicolored with unique patterns." },
  { id: 53, name: "Jet", slug: "jet", image: "/images/gemstones/placeholder.jpg", shortDesc: "Fossilized wood, black organic gem, Victorian mourning jewelry." },
  { id: 54, name: "K2 Granite", slug: "k2-granite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Granite with blue azurite spots, found near K2 mountain." },
  { id: 55, name: "Kunzite", slug: "kunzite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Pink to violet spodumene, known for its pleochroism." },
  { id: 56, name: "Kyanite", slug: "kyanite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Blue gem with anisotropic hardness, often in blades." },
  { id: 57, name: "Labradorite", slug: "labradorite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Feldspar with spectacular iridescent labradorescence." },
  { id: 58, name: "Lapis Lazuli", slug: "lapis-lazuli", image: "/images/gemstones/placeholder.jpg", shortDesc: "Deep blue rock with pyrite flecks, prized since ancient times." },
  { id: 59, name: "Larimar", slug: "larimar", image: "/images/gemstones/placeholder.jpg", shortDesc: "Blue pectolite, found only in the Dominican Republic." },
  { id: 60, name: "Lepidolite", slug: "lepidolite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Lithium mica, purple to pink, often used for calming." },
  { id: 61, name: "Malachite", slug: "malachite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Green copper carbonate with distinctive banded patterns." },
  { id: 62, name: "Maw Sit Sit", slug: "maw-sit-sit", image: "/images/gemstones/placeholder.jpg", shortDesc: "Green metamorphic rock from Myanmar, chromium-rich." },
  { id: 63, name: "Moldavite", slug: "moldavite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Green tektite from meteorite impact, found in Czech Republic." },
  { id: 64, name: "Moonstone", slug: "moonstone", image: "/images/gemstones/placeholder.jpg", shortDesc: "Feldspar with adularescence, June birthstone." },
  { id: 65, name: "Morganite", slug: "morganite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Pink to peach beryl, popular for engagement rings." },
  { id: 66, name: "Nephrite", slug: "nephrite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Commoner form of jade, typically dark green." },
  { id: 67, name: "Obsidian", slug: "obsidian", image: "/images/gemstones/placeholder.jpg", shortDesc: "Volcanic glass, black with conchoidal fracture." },
  { id: 68, name: "Onyx", slug: "onyx", image: "/images/gemstones/placeholder.jpg", shortDesc: "Black and white banded chalcedony, often used for cameos." },
  { id: 69, name: "Opal", slug: "opal", image: "/images/gemstones/placeholder.jpg", shortDesc: "October birthstone with play-of-color, hydrated silica." },
  { id: 70, name: "Opalite", slug: "opalite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Man-made glass that mimics opal, also a natural opal variety." },
  { id: 71, name: "Organic Gems", slug: "organic-gems", image: "/images/gemstones/placeholder.jpg", shortDesc: "Pearls, amber, coral, jet – gems from living organisms." },
  { id: 72, name: "Palm Wood", slug: "palm-wood", image: "/images/gemstones/placeholder.jpg", shortDesc: "Fossilized palm wood, often agatized." },
  { id: 73, name: "Peanut Wood", slug: "peanut-wood", image: "/images/gemstones/placeholder.jpg", shortDesc: "Fossilized wood with peanut-like patterns." },
  { id: 74, name: "Peridot", slug: "peridot", image: "/images/gemstones/placeholder.jpg", shortDesc: "Yellow-green olivine, August birthstone, 'gem of the sun'." },
  { id: 75, name: "Petrified Wood", slug: "petrified-wood", image: "/images/gemstones/placeholder.jpg", shortDesc: "Fossilized wood replaced by quartz or agate." },
  { id: 76, name: "Pinolith", slug: "pinolith", image: "/images/gemstones/placeholder.jpg", shortDesc: "Black and white pinolite, ornamental stone from Austria." },
  { id: 77, name: "Polka Dot Agate", slug: "polka-dot-agate", image: "/images/gemstones/placeholder.jpg", shortDesc: "Agate with white orbs on gray background, from Oregon." },
  { id: 78, name: "Prasiolite", slug: "prasiolite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Green quartz, also called green amethyst (heat-treated)." },
  { id: 79, name: "Precious Opal", slug: "precious-opal", image: "/images/gemstones/placeholder.jpg", shortDesc: "Opal that displays play-of-color, highly valued." },
  { id: 80, name: "Pyrite", slug: "pyrite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Fool's gold, metallic cubic crystals used in jewelry." },
  { id: 81, name: "Quartz", slug: "quartz", image: "/images/gemstones/placeholder.jpg", shortDesc: "Abundant mineral, many varieties: amethyst, citrine, rose." },
  { id: 82, name: "Red Beryl", slug: "red-beryl", image: "/images/gemstones/placeholder.jpg", shortDesc: "Rare red beryl, also called bixbite, from Utah." },
  { id: 83, name: "Rhodochrosite", slug: "rhodochrosite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Pink to red banded manganese carbonate, Argentina's national gem." },
  { id: 84, name: "Rhodonite", slug: "rhodonite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Pink manganese silicate with black veins." },
  { id: 85, name: "Rose Quartz", slug: "rose-quartz", image: "/images/gemstones/placeholder.jpg", shortDesc: "Pink quartz, stone of love, often massive." },
  { id: 86, name: "Ruby", slug: "ruby", image: "/images/gemstones/placeholder.jpg", shortDesc: "Red corundum, July birthstone, one of the 'big three'." },
  { id: 87, name: "Ruby in Zoisite", slug: "ruby-in-zoisite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Green zoisite with red ruby crystals, also called anyolite." },
  { id: 88, name: "Sapphire", slug: "sapphire", image: "/images/gemstones/placeholder.jpg", shortDesc: "Blue corundum, September birthstone, second hardest gem." },
  { id: 89, name: "Scapolite", slug: "scapolite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Yellow to purple gem, often fluorescent." },
  { id: 90, name: "Serpentine", slug: "serpentine", image: "/images/gemstones/placeholder.jpg", shortDesc: "Green to yellow mineral, used as jade simulant." },
  { id: 91, name: "Smithsonite", slug: "smithsonite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Zinc carbonate, blue to pink, with botryoidal habit." },
  { id: 92, name: "Smoky Quartz", slug: "smoky-quartz", image: "/images/gemstones/placeholder.jpg", shortDesc: "Brown to black quartz, color from natural irradiation." },
  { id: 93, name: "Sodalite", slug: "sodalite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Blue feldspathoid with white calcite veining." },
  { id: 94, name: "Sonora Sunrise", slug: "sonora-sunrise", image: "/images/gemstones/placeholder.jpg", shortDesc: "Red and green chalcedony from Mexico." },
  { id: 95, name: "Sphalerite", slug: "sphalerite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Zinc ore, high dispersion but soft, prized by collectors." },
  { id: 96, name: "Sphene", slug: "sphene", image: "/images/gemstones/placeholder.jpg", shortDesc: "Titanite, yellow to green, high fire and dispersion." },
  { id: 97, name: "Spinel", slug: "spinel", image: "/images/gemstones/placeholder.jpg", shortDesc: "August birthstone, often mistaken for ruby." },
  { id: 98, name: "Spodumene", slug: "spodumene", image: "/images/gemstones/placeholder.jpg", shortDesc: "Includes kunzite (pink) and hiddenite (green)." },
  { id: 99, name: "Strawberry Quartz", slug: "strawberry-quartz", image: "/images/gemstones/placeholder.jpg", shortDesc: "Quartz with red inclusions resembling strawberry seeds." },
  { id: 100, name: "Strontium Titanate", slug: "strontium-titanate", image: "/images/gemstones/placeholder.jpg", shortDesc: "Synthetic diamond simulant with high dispersion." },
  { id: 101, name: "Sugilite", slug: "sugilite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Rare purple cyclosilicate, found in South Africa and Japan." },
  { id: 102, name: "Sunstone", slug: "sunstone", image: "/images/gemstones/placeholder.jpg", shortDesc: "Feldspar with glittering aventurescence, Oregon state gem." },
  { id: 103, name: "Tanzanite", slug: "tanzanite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Blue zoisite, found only in Tanzania, December birthstone." },
  { id: 104, name: "Tiger's Eye", slug: "tigers-eye", image: "/images/gemstones/placeholder.jpg", shortDesc: "Chatoyant quartz, golden-brown, often used for cabochons." },
  { id: 105, name: "Tiffany Stone", slug: "tiffany-stone", image: "/images/gemstones/placeholder.jpg", shortDesc: "Rare purple opalized fluorite from Utah." },
  { id: 106, name: "Titanite", slug: "titanite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Also called sphene, yellow-green with high fire." },
  { id: 107, name: "Topaz", slug: "topaz", image: "/images/gemstones/placeholder.jpg", shortDesc: "November birthstone, comes in many colors, hardest silicate." },
  { id: 108, name: "Tourmaline", slug: "tourmaline", image: "/images/gemstones/placeholder.jpg", shortDesc: "October birthstone, occurs in more colors than any mineral." },
  { id: 109, name: "Turquoise", slug: "turquoise", image: "/images/gemstones/placeholder.jpg", shortDesc: "Blue to green phosphate, December birthstone." },
  { id: 110, name: "Turritella Agate", slug: "turritella-agate", image: "/images/gemstones/placeholder.jpg", shortDesc: "Agate with fossil snail shells, from Wyoming." },
  { id: 111, name: "Unakite", slug: "unakite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Pink feldspar and green epidote, used for cabochons." },
  { id: 112, name: "Uvarovite", slug: "uvarovite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Green garnet, rarely found as facetable crystals." },
  { id: 113, name: "Variscite", slug: "variscite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Green to blue-green phosphate, similar to turquoise." },
  { id: 114, name: "Vesuvianite", slug: "vesuvianite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Also called idocrase, green, yellow, brown gem." },
  { id: 115, name: "Watermelon Tourmaline", slug: "watermelon-tourmaline", image: "/images/gemstones/placeholder.jpg", shortDesc: "Tourmaline with green rind and pink core, like a watermelon." },
  { id: 116, name: "Wonderstone", slug: "wonderstone", image: "/images/gemstones/placeholder.jpg", shortDesc: "Rhyolite with colorful banded patterns." },
  { id: 117, name: "Yellow Sapphire", slug: "yellow-sapphire", image: "/images/gemstones/placeholder.jpg", shortDesc: "Yellow variety of corundum, also called pukhraj." },
  { id: 118, name: "Zebra Jasper", slug: "zebra-jasper", image: "/images/gemstones/placeholder.jpg", shortDesc: "Black and white banded jasper from South Africa." },
  { id: 119, name: "Zincite", slug: "zincite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Red to orange zinc oxide, often synthetic." },
  { id: 120, name: "Zircon", slug: "zircon", image: "/images/gemstones/placeholder.jpg", shortDesc: "December birthstone, brilliant, often confused with cubic zirconia." },
  { id: 121, name: "Zoisite", slug: "zoisite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Includes tanzanite (blue) and anyolite (green with ruby)." },
  { id: 122, name: "Agate", slug: "agate", image: "/images/gemstones/placeholder.jpg", shortDesc: "Banded chalcedony, found in many colors and patterns." },
  { id: 123, name: "Alexandrite", slug: "alexandrite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Chrysoberyl that changes color from green to red." },
  { id: 124, name: "Andradite", slug: "andradite", image: "/images/gemstones/placeholder.jpg", shortDesc: "Green garnet, includes demantoid and topazolite." }
];